name: "Maintenance"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: C++ code linter (clang-tidy and cppcheck)
        uses: tonybaloney/cpp-linter-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}